// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rj/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebf06b5b001cb49, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebf06b5b001cb49, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetSectionIdRequest struct {
}

func (m *QueryGetSectionIdRequest) Reset()         { *m = QueryGetSectionIdRequest{} }
func (m *QueryGetSectionIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSectionIdRequest) ProtoMessage()    {}
func (*QueryGetSectionIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebf06b5b001cb49, []int{2}
}
func (m *QueryGetSectionIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSectionIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSectionIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSectionIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSectionIdRequest.Merge(m, src)
}
func (m *QueryGetSectionIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSectionIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSectionIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSectionIdRequest proto.InternalMessageInfo

type QueryGetSectionIdResponse struct {
	SectionId SectionId `protobuf:"bytes,1,opt,name=SectionId,proto3" json:"SectionId"`
}

func (m *QueryGetSectionIdResponse) Reset()         { *m = QueryGetSectionIdResponse{} }
func (m *QueryGetSectionIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSectionIdResponse) ProtoMessage()    {}
func (*QueryGetSectionIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebf06b5b001cb49, []int{3}
}
func (m *QueryGetSectionIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSectionIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSectionIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSectionIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSectionIdResponse.Merge(m, src)
}
func (m *QueryGetSectionIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSectionIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSectionIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSectionIdResponse proto.InternalMessageInfo

func (m *QueryGetSectionIdResponse) GetSectionId() SectionId {
	if m != nil {
		return m.SectionId
	}
	return SectionId{}
}

type QueryGetTopicIdRequest struct {
}

func (m *QueryGetTopicIdRequest) Reset()         { *m = QueryGetTopicIdRequest{} }
func (m *QueryGetTopicIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetTopicIdRequest) ProtoMessage()    {}
func (*QueryGetTopicIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebf06b5b001cb49, []int{4}
}
func (m *QueryGetTopicIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTopicIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTopicIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTopicIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTopicIdRequest.Merge(m, src)
}
func (m *QueryGetTopicIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTopicIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTopicIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTopicIdRequest proto.InternalMessageInfo

type QueryGetTopicIdResponse struct {
	TopicId TopicId `protobuf:"bytes,1,opt,name=TopicId,proto3" json:"TopicId"`
}

func (m *QueryGetTopicIdResponse) Reset()         { *m = QueryGetTopicIdResponse{} }
func (m *QueryGetTopicIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetTopicIdResponse) ProtoMessage()    {}
func (*QueryGetTopicIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebf06b5b001cb49, []int{5}
}
func (m *QueryGetTopicIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTopicIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTopicIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTopicIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTopicIdResponse.Merge(m, src)
}
func (m *QueryGetTopicIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTopicIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTopicIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTopicIdResponse proto.InternalMessageInfo

func (m *QueryGetTopicIdResponse) GetTopicId() TopicId {
	if m != nil {
		return m.TopicId
	}
	return TopicId{}
}

type QueryGetPostIdRequest struct {
}

func (m *QueryGetPostIdRequest) Reset()         { *m = QueryGetPostIdRequest{} }
func (m *QueryGetPostIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPostIdRequest) ProtoMessage()    {}
func (*QueryGetPostIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebf06b5b001cb49, []int{6}
}
func (m *QueryGetPostIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPostIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPostIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPostIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPostIdRequest.Merge(m, src)
}
func (m *QueryGetPostIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPostIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPostIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPostIdRequest proto.InternalMessageInfo

type QueryGetPostIdResponse struct {
	PostId PostId `protobuf:"bytes,1,opt,name=PostId,proto3" json:"PostId"`
}

func (m *QueryGetPostIdResponse) Reset()         { *m = QueryGetPostIdResponse{} }
func (m *QueryGetPostIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPostIdResponse) ProtoMessage()    {}
func (*QueryGetPostIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebf06b5b001cb49, []int{7}
}
func (m *QueryGetPostIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPostIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPostIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPostIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPostIdResponse.Merge(m, src)
}
func (m *QueryGetPostIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPostIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPostIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPostIdResponse proto.InternalMessageInfo

func (m *QueryGetPostIdResponse) GetPostId() PostId {
	if m != nil {
		return m.PostId
	}
	return PostId{}
}

type QueryGetSectionRequest struct {
	SectionId uint64 `protobuf:"varint,1,opt,name=sectionId,proto3" json:"sectionId,omitempty"`
}

func (m *QueryGetSectionRequest) Reset()         { *m = QueryGetSectionRequest{} }
func (m *QueryGetSectionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSectionRequest) ProtoMessage()    {}
func (*QueryGetSectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebf06b5b001cb49, []int{8}
}
func (m *QueryGetSectionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSectionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSectionRequest.Merge(m, src)
}
func (m *QueryGetSectionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSectionRequest proto.InternalMessageInfo

func (m *QueryGetSectionRequest) GetSectionId() uint64 {
	if m != nil {
		return m.SectionId
	}
	return 0
}

type QueryGetSectionResponse struct {
	Section Section `protobuf:"bytes,1,opt,name=section,proto3" json:"section"`
}

func (m *QueryGetSectionResponse) Reset()         { *m = QueryGetSectionResponse{} }
func (m *QueryGetSectionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSectionResponse) ProtoMessage()    {}
func (*QueryGetSectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebf06b5b001cb49, []int{9}
}
func (m *QueryGetSectionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSectionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSectionResponse.Merge(m, src)
}
func (m *QueryGetSectionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSectionResponse proto.InternalMessageInfo

func (m *QueryGetSectionResponse) GetSection() Section {
	if m != nil {
		return m.Section
	}
	return Section{}
}

type QueryAllSectionRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSectionRequest) Reset()         { *m = QueryAllSectionRequest{} }
func (m *QueryAllSectionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllSectionRequest) ProtoMessage()    {}
func (*QueryAllSectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebf06b5b001cb49, []int{10}
}
func (m *QueryAllSectionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSectionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSectionRequest.Merge(m, src)
}
func (m *QueryAllSectionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSectionRequest proto.InternalMessageInfo

func (m *QueryAllSectionRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllSectionResponse struct {
	Section    []Section           `protobuf:"bytes,1,rep,name=section,proto3" json:"section"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSectionResponse) Reset()         { *m = QueryAllSectionResponse{} }
func (m *QueryAllSectionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllSectionResponse) ProtoMessage()    {}
func (*QueryAllSectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ebf06b5b001cb49, []int{11}
}
func (m *QueryAllSectionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSectionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSectionResponse.Merge(m, src)
}
func (m *QueryAllSectionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSectionResponse proto.InternalMessageInfo

func (m *QueryAllSectionResponse) GetSection() []Section {
	if m != nil {
		return m.Section
	}
	return nil
}

func (m *QueryAllSectionResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "rj.rj.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "rj.rj.QueryParamsResponse")
	proto.RegisterType((*QueryGetSectionIdRequest)(nil), "rj.rj.QueryGetSectionIdRequest")
	proto.RegisterType((*QueryGetSectionIdResponse)(nil), "rj.rj.QueryGetSectionIdResponse")
	proto.RegisterType((*QueryGetTopicIdRequest)(nil), "rj.rj.QueryGetTopicIdRequest")
	proto.RegisterType((*QueryGetTopicIdResponse)(nil), "rj.rj.QueryGetTopicIdResponse")
	proto.RegisterType((*QueryGetPostIdRequest)(nil), "rj.rj.QueryGetPostIdRequest")
	proto.RegisterType((*QueryGetPostIdResponse)(nil), "rj.rj.QueryGetPostIdResponse")
	proto.RegisterType((*QueryGetSectionRequest)(nil), "rj.rj.QueryGetSectionRequest")
	proto.RegisterType((*QueryGetSectionResponse)(nil), "rj.rj.QueryGetSectionResponse")
	proto.RegisterType((*QueryAllSectionRequest)(nil), "rj.rj.QueryAllSectionRequest")
	proto.RegisterType((*QueryAllSectionResponse)(nil), "rj.rj.QueryAllSectionResponse")
}

func init() { proto.RegisterFile("rj/query.proto", fileDescriptor_4ebf06b5b001cb49) }

var fileDescriptor_4ebf06b5b001cb49 = []byte{
	// 623 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xe3, 0x92, 0xa6, 0xea, 0xa2, 0x7c, 0x6d, 0xda, 0x26, 0xb1, 0x52, 0xb7, 0xf2, 0x81,
	0x22, 0x90, 0xbc, 0x6a, 0x41, 0xdc, 0x1b, 0x09, 0xaa, 0xde, 0xd2, 0x80, 0x38, 0x20, 0x21, 0x70,
	0x52, 0xcb, 0xb2, 0xe5, 0x66, 0x5d, 0xaf, 0x8b, 0xa8, 0x10, 0x17, 0x9e, 0x00, 0xc1, 0x4b, 0xf5,
	0x58, 0x89, 0x0b, 0x27, 0x40, 0x09, 0x0f, 0x52, 0x79, 0x77, 0xd6, 0xeb, 0x8f, 0x44, 0xbd, 0xd9,
	0xff, 0xf9, 0xf8, 0xcd, 0x8c, 0x66, 0x16, 0x35, 0x22, 0x9f, 0x5c, 0x5e, 0x39, 0xd1, 0xb5, 0x15,
	0x46, 0x34, 0xa6, 0x78, 0x3d, 0xf2, 0xad, 0xc8, 0xd7, 0xb7, 0x5c, 0xea, 0x52, 0xae, 0x90, 0xe4,
	0x4b, 0x18, 0xf5, 0x81, 0x4b, 0xa9, 0x1b, 0x38, 0xc4, 0x0e, 0x3d, 0x62, 0xcf, 0x66, 0x34, 0xb6,
	0x63, 0x8f, 0xce, 0x18, 0x58, 0x9f, 0x4c, 0x29, 0xbb, 0xa0, 0x8c, 0x4c, 0x6c, 0xe6, 0x88, 0x9c,
	0xe4, 0xd3, 0xe1, 0xc4, 0x89, 0xed, 0x43, 0x12, 0xda, 0xae, 0x37, 0xe3, 0xce, 0xe0, 0xdb, 0x8c,
	0x7c, 0x12, 0xda, 0x91, 0x7d, 0x21, 0x83, 0x3b, 0x91, 0x4f, 0x98, 0x33, 0x4d, 0x5c, 0x3e, 0x78,
	0xe7, 0x20, 0xb6, 0x23, 0x9f, 0xc4, 0x34, 0xf4, 0xa6, 0x4a, 0x6a, 0x25, 0x81, 0x94, 0xc5, 0x79,
	0x05, 0x22, 0x85, 0x62, 0x6e, 0x21, 0x7c, 0x96, 0xe0, 0x47, 0x1c, 0x30, 0x76, 0x2e, 0xaf, 0x1c,
	0x16, 0x9b, 0x43, 0xd4, 0xc9, 0xa9, 0x2c, 0xa4, 0x33, 0xe6, 0xe0, 0xa7, 0xa8, 0x26, 0x0a, 0xe9,
	0x69, 0xfb, 0xda, 0xe3, 0x87, 0x47, 0x75, 0x8b, 0x4f, 0xc0, 0x12, 0x6e, 0xc3, 0xea, 0xcd, 0x9f,
	0xbd, 0xca, 0x18, 0x5c, 0x4c, 0x1d, 0xf5, 0x78, 0x8e, 0x13, 0x27, 0x7e, 0x2d, 0x90, 0xa7, 0xe7,
	0x32, 0xff, 0x19, 0xea, 0x2f, 0xb1, 0x01, 0xe5, 0x39, 0xda, 0x4c, 0x45, 0x00, 0xb5, 0x00, 0x94,
	0xea, 0xc0, 0x52, 0x8e, 0x66, 0x0f, 0xed, 0xc8, 0x94, 0x6f, 0x92, 0x31, 0x28, 0xd8, 0x29, 0xea,
	0x96, 0x2c, 0x80, 0xb2, 0xd0, 0x06, 0x48, 0x00, 0x6a, 0x00, 0x08, 0x54, 0xc0, 0x48, 0x27, 0xb3,
	0x8b, 0xb6, 0x65, 0xaa, 0x11, 0x65, 0xb1, 0x62, 0xbc, 0x54, 0x74, 0x69, 0x50, 0x33, 0x13, 0x4a,
	0x71, 0x66, 0x5c, 0x94, 0x33, 0x13, 0x7f, 0xe6, 0x0b, 0x95, 0x06, 0x3a, 0x03, 0x00, 0x1e, 0xa0,
	0x4d, 0x96, 0x1b, 0x4a, 0x75, 0xac, 0x84, 0x6c, 0x8b, 0x69, 0x9c, 0x6a, 0x11, 0xfc, 0x0a, 0x2d,
	0x82, 0xa3, 0x6c, 0x11, 0x9c, 0xcc, 0x8f, 0x50, 0xc2, 0x71, 0x10, 0x14, 0x4a, 0x78, 0x85, 0x90,
	0xda, 0x4d, 0x48, 0xf6, 0xc8, 0x12, 0x8b, 0x6c, 0x25, 0x8b, 0x6c, 0x89, 0xe3, 0x80, 0x45, 0xb6,
	0x46, 0xb6, 0xeb, 0x40, 0xec, 0x38, 0x13, 0x69, 0xfe, 0xd0, 0xa0, 0xda, 0x2c, 0x62, 0x59, 0xb5,
	0x0f, 0xee, 0xad, 0x16, 0x9f, 0xe4, 0x6a, 0x5a, 0xe3, 0x35, 0x1d, 0xdc, 0x5b, 0x93, 0x80, 0x65,
	0x8b, 0x3a, 0xfa, 0x5b, 0x45, 0xeb, 0xbc, 0x28, 0xfc, 0x16, 0xd5, 0xc4, 0x3e, 0xe3, 0x3e, 0xb0,
	0xcb, 0x07, 0xa2, 0xeb, 0xcb, 0x4c, 0x22, 0xad, 0xb9, 0xfd, 0xed, 0xd7, 0xff, 0x9f, 0x6b, 0x4d,
	0x5c, 0x27, 0x91, 0x4f, 0xd2, 0xdb, 0xc5, 0x5e, 0x66, 0xad, 0xf1, 0x5e, 0x36, 0x7e, 0xc9, 0x85,
	0xe8, 0xfb, 0xab, 0x1d, 0x00, 0xd3, 0xe7, 0x98, 0x0e, 0x6e, 0x03, 0x46, 0xbd, 0x08, 0xd8, 0x4e,
	0xd7, 0x1a, 0xef, 0x16, 0xf2, 0xe4, 0x6f, 0x43, 0x37, 0x56, 0x99, 0x01, 0xd2, 0xe5, 0x90, 0x36,
	0x6e, 0x02, 0x44, 0xbe, 0x30, 0xf8, 0xbd, 0x5c, 0x6b, 0x3c, 0x28, 0xa4, 0xc8, 0x1d, 0x86, 0xbe,
	0xbb, 0xc2, 0x0a, 0xf9, 0x77, 0x78, 0xfe, 0x16, 0x6e, 0xc8, 0x59, 0x89, 0xe7, 0x0a, 0x07, 0x68,
	0x03, 0x3a, 0x2e, 0x75, 0x90, 0xdf, 0xca, 0x52, 0x07, 0x85, 0x8d, 0x32, 0x4d, 0x4e, 0x18, 0x60,
	0x3d, 0x3f, 0x26, 0xf2, 0x25, 0xbd, 0x9e, 0xaf, 0x78, 0x8a, 0x10, 0x84, 0x1d, 0x07, 0x41, 0x1e,
	0x58, 0x3a, 0x83, 0x3c, 0xb0, 0xbc, 0xc2, 0xa5, 0x96, 0x80, 0x33, 0x3c, 0xb8, 0x99, 0x1b, 0xda,
	0xed, 0xdc, 0xd0, 0xfe, 0xcd, 0x0d, 0xed, 0xfb, 0xc2, 0xa8, 0xdc, 0x2e, 0x8c, 0xca, 0xef, 0x85,
	0x51, 0x79, 0x57, 0x8f, 0x7c, 0xf2, 0x99, 0x4f, 0xf7, 0x3a, 0x74, 0xd8, 0xa4, 0xc6, 0x5f, 0xe6,
	0x67, 0x77, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x26, 0x9f, 0xb5, 0x6f, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a SectionId by index.
	SectionId(ctx context.Context, in *QueryGetSectionIdRequest, opts ...grpc.CallOption) (*QueryGetSectionIdResponse, error)
	// Queries a TopicId by index.
	TopicId(ctx context.Context, in *QueryGetTopicIdRequest, opts ...grpc.CallOption) (*QueryGetTopicIdResponse, error)
	// Queries a PostId by index.
	PostId(ctx context.Context, in *QueryGetPostIdRequest, opts ...grpc.CallOption) (*QueryGetPostIdResponse, error)
	// Queries a Section by index.
	Section(ctx context.Context, in *QueryGetSectionRequest, opts ...grpc.CallOption) (*QueryGetSectionResponse, error)
	// Queries a list of Section items.
	SectionAll(ctx context.Context, in *QueryAllSectionRequest, opts ...grpc.CallOption) (*QueryAllSectionResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/rj.rj.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SectionId(ctx context.Context, in *QueryGetSectionIdRequest, opts ...grpc.CallOption) (*QueryGetSectionIdResponse, error) {
	out := new(QueryGetSectionIdResponse)
	err := c.cc.Invoke(ctx, "/rj.rj.Query/SectionId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TopicId(ctx context.Context, in *QueryGetTopicIdRequest, opts ...grpc.CallOption) (*QueryGetTopicIdResponse, error) {
	out := new(QueryGetTopicIdResponse)
	err := c.cc.Invoke(ctx, "/rj.rj.Query/TopicId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PostId(ctx context.Context, in *QueryGetPostIdRequest, opts ...grpc.CallOption) (*QueryGetPostIdResponse, error) {
	out := new(QueryGetPostIdResponse)
	err := c.cc.Invoke(ctx, "/rj.rj.Query/PostId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Section(ctx context.Context, in *QueryGetSectionRequest, opts ...grpc.CallOption) (*QueryGetSectionResponse, error) {
	out := new(QueryGetSectionResponse)
	err := c.cc.Invoke(ctx, "/rj.rj.Query/Section", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SectionAll(ctx context.Context, in *QueryAllSectionRequest, opts ...grpc.CallOption) (*QueryAllSectionResponse, error) {
	out := new(QueryAllSectionResponse)
	err := c.cc.Invoke(ctx, "/rj.rj.Query/SectionAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a SectionId by index.
	SectionId(context.Context, *QueryGetSectionIdRequest) (*QueryGetSectionIdResponse, error)
	// Queries a TopicId by index.
	TopicId(context.Context, *QueryGetTopicIdRequest) (*QueryGetTopicIdResponse, error)
	// Queries a PostId by index.
	PostId(context.Context, *QueryGetPostIdRequest) (*QueryGetPostIdResponse, error)
	// Queries a Section by index.
	Section(context.Context, *QueryGetSectionRequest) (*QueryGetSectionResponse, error)
	// Queries a list of Section items.
	SectionAll(context.Context, *QueryAllSectionRequest) (*QueryAllSectionResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) SectionId(ctx context.Context, req *QueryGetSectionIdRequest) (*QueryGetSectionIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SectionId not implemented")
}
func (*UnimplementedQueryServer) TopicId(ctx context.Context, req *QueryGetTopicIdRequest) (*QueryGetTopicIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TopicId not implemented")
}
func (*UnimplementedQueryServer) PostId(ctx context.Context, req *QueryGetPostIdRequest) (*QueryGetPostIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostId not implemented")
}
func (*UnimplementedQueryServer) Section(ctx context.Context, req *QueryGetSectionRequest) (*QueryGetSectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Section not implemented")
}
func (*UnimplementedQueryServer) SectionAll(ctx context.Context, req *QueryAllSectionRequest) (*QueryAllSectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SectionAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rj.rj.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SectionId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSectionIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SectionId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rj.rj.Query/SectionId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SectionId(ctx, req.(*QueryGetSectionIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TopicId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetTopicIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TopicId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rj.rj.Query/TopicId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TopicId(ctx, req.(*QueryGetTopicIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PostId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPostIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PostId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rj.rj.Query/PostId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PostId(ctx, req.(*QueryGetPostIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Section_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Section(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rj.rj.Query/Section",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Section(ctx, req.(*QueryGetSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SectionAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SectionAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rj.rj.Query/SectionAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SectionAll(ctx, req.(*QueryAllSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rj.rj.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "SectionId",
			Handler:    _Query_SectionId_Handler,
		},
		{
			MethodName: "TopicId",
			Handler:    _Query_TopicId_Handler,
		},
		{
			MethodName: "PostId",
			Handler:    _Query_PostId_Handler,
		},
		{
			MethodName: "Section",
			Handler:    _Query_Section_Handler,
		},
		{
			MethodName: "SectionAll",
			Handler:    _Query_SectionAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rj/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetSectionIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSectionIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSectionIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetSectionIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSectionIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSectionIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.SectionId.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetTopicIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTopicIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTopicIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetTopicIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTopicIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTopicIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TopicId.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetPostIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPostIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPostIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetPostIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPostIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPostIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.PostId.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetSectionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSectionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSectionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SectionId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.SectionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSectionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSectionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSectionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Section.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllSectionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSectionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSectionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllSectionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSectionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSectionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Section) > 0 {
		for iNdEx := len(m.Section) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Section[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetSectionIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetSectionIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SectionId.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetTopicIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetTopicIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TopicId.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetPostIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetPostIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PostId.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetSectionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SectionId != 0 {
		n += 1 + sovQuery(uint64(m.SectionId))
	}
	return n
}

func (m *QueryGetSectionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Section.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllSectionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllSectionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Section) > 0 {
		for _, e := range m.Section {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSectionIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSectionIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSectionIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSectionIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSectionIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSectionIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SectionId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SectionId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTopicIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTopicIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTopicIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTopicIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTopicIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTopicIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TopicId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TopicId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPostIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPostIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPostIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPostIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPostIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPostIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PostId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSectionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSectionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSectionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SectionId", wireType)
			}
			m.SectionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SectionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSectionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSectionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSectionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Section", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Section.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSectionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSectionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSectionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSectionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSectionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSectionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Section", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Section = append(m.Section, Section{})
			if err := m.Section[len(m.Section)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
