// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rj/section_topic.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SectionTopic struct {
	SectionId uint64   `protobuf:"varint,1,opt,name=sectionId,proto3" json:"sectionId,omitempty"`
	Topics    []uint64 `protobuf:"varint,2,rep,packed,name=topics,proto3" json:"topics,omitempty"`
}

func (m *SectionTopic) Reset()         { *m = SectionTopic{} }
func (m *SectionTopic) String() string { return proto.CompactTextString(m) }
func (*SectionTopic) ProtoMessage()    {}
func (*SectionTopic) Descriptor() ([]byte, []int) {
	return fileDescriptor_107b2189bc07f596, []int{0}
}
func (m *SectionTopic) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SectionTopic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SectionTopic.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SectionTopic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SectionTopic.Merge(m, src)
}
func (m *SectionTopic) XXX_Size() int {
	return m.Size()
}
func (m *SectionTopic) XXX_DiscardUnknown() {
	xxx_messageInfo_SectionTopic.DiscardUnknown(m)
}

var xxx_messageInfo_SectionTopic proto.InternalMessageInfo

func (m *SectionTopic) GetSectionId() uint64 {
	if m != nil {
		return m.SectionId
	}
	return 0
}

func (m *SectionTopic) GetTopics() []uint64 {
	if m != nil {
		return m.Topics
	}
	return nil
}

func init() {
	proto.RegisterType((*SectionTopic)(nil), "rj.rj.SectionTopic")
}

func init() { proto.RegisterFile("rj/section_topic.proto", fileDescriptor_107b2189bc07f596) }

var fileDescriptor_107b2189bc07f596 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0xca, 0xd2, 0x2f,
	0x4e, 0x4d, 0x2e, 0xc9, 0xcc, 0xcf, 0x8b, 0x2f, 0xc9, 0x2f, 0xc8, 0x4c, 0xd6, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x2d, 0xca, 0xd2, 0x2b, 0xca, 0x52, 0x72, 0xe1, 0xe2, 0x09, 0x86, 0xc8,
	0x86, 0x80, 0x24, 0x85, 0x64, 0xb8, 0x38, 0xa1, 0xaa, 0x3d, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35,
	0x58, 0x82, 0x10, 0x02, 0x42, 0x62, 0x5c, 0x6c, 0x60, 0x33, 0x8a, 0x25, 0x98, 0x14, 0x98, 0x35,
	0x58, 0x82, 0xa0, 0x3c, 0x27, 0xf5, 0x13, 0x8f, 0xe4, 0x18, 0x2f, 0x3c, 0x92, 0x63, 0x7c, 0xf0,
	0x48, 0x8e, 0x71, 0xc2, 0x63, 0x39, 0x86, 0x0b, 0x8f, 0xe5, 0x18, 0x6e, 0x3c, 0x96, 0x63, 0x88,
	0xe2, 0x2d, 0xca, 0xd2, 0xaf, 0xd0, 0x2f, 0xca, 0xd2, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0x4e, 0x62,
	0x03, 0x5b, 0x6e, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x75, 0x01, 0x93, 0x45, 0x96, 0x00, 0x00,
	0x00,
}

func (m *SectionTopic) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SectionTopic) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SectionTopic) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Topics) > 0 {
		dAtA2 := make([]byte, len(m.Topics)*10)
		var j1 int
		for _, num := range m.Topics {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintSectionTopic(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x12
	}
	if m.SectionId != 0 {
		i = encodeVarintSectionTopic(dAtA, i, uint64(m.SectionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSectionTopic(dAtA []byte, offset int, v uint64) int {
	offset -= sovSectionTopic(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SectionTopic) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SectionId != 0 {
		n += 1 + sovSectionTopic(uint64(m.SectionId))
	}
	if len(m.Topics) > 0 {
		l = 0
		for _, e := range m.Topics {
			l += sovSectionTopic(uint64(e))
		}
		n += 1 + sovSectionTopic(uint64(l)) + l
	}
	return n
}

func sovSectionTopic(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSectionTopic(x uint64) (n int) {
	return sovSectionTopic(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SectionTopic) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSectionTopic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SectionTopic: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SectionTopic: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SectionId", wireType)
			}
			m.SectionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSectionTopic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SectionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSectionTopic
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Topics = append(m.Topics, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSectionTopic
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthSectionTopic
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthSectionTopic
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Topics) == 0 {
					m.Topics = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSectionTopic
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Topics = append(m.Topics, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Topics", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSectionTopic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSectionTopic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSectionTopic(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSectionTopic
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSectionTopic
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSectionTopic
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSectionTopic
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSectionTopic
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSectionTopic
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSectionTopic        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSectionTopic          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSectionTopic = fmt.Errorf("proto: unexpected end of group")
)
