// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rj/section_id.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SectionId struct {
	SectionId uint64 `protobuf:"varint,1,opt,name=sectionId,proto3" json:"sectionId,omitempty"`
}

func (m *SectionId) Reset()         { *m = SectionId{} }
func (m *SectionId) String() string { return proto.CompactTextString(m) }
func (*SectionId) ProtoMessage()    {}
func (*SectionId) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b8f8b18507a218f, []int{0}
}
func (m *SectionId) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SectionId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SectionId.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SectionId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SectionId.Merge(m, src)
}
func (m *SectionId) XXX_Size() int {
	return m.Size()
}
func (m *SectionId) XXX_DiscardUnknown() {
	xxx_messageInfo_SectionId.DiscardUnknown(m)
}

var xxx_messageInfo_SectionId proto.InternalMessageInfo

func (m *SectionId) GetSectionId() uint64 {
	if m != nil {
		return m.SectionId
	}
	return 0
}

func init() {
	proto.RegisterType((*SectionId)(nil), "rj.rj.SectionId")
}

func init() { proto.RegisterFile("rj/section_id.proto", fileDescriptor_8b8f8b18507a218f) }

var fileDescriptor_8b8f8b18507a218f = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0xca, 0xd2, 0x2f,
	0x4e, 0x4d, 0x2e, 0xc9, 0xcc, 0xcf, 0x8b, 0xcf, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x2d, 0xca, 0xd2, 0x2b, 0xca, 0x52, 0xd2, 0xe4, 0xe2, 0x0c, 0x86, 0x48, 0x79, 0xa6, 0x08,
	0xc9, 0x70, 0x71, 0x16, 0xc3, 0x38, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x08, 0x01, 0x27,
	0xf5, 0x13, 0x8f, 0xe4, 0x18, 0x2f, 0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc2, 0x63,
	0x39, 0x86, 0x0b, 0x8f, 0xe5, 0x18, 0x6e, 0x3c, 0x96, 0x63, 0x88, 0xe2, 0x2d, 0xca, 0xd2, 0xaf,
	0xd0, 0x2f, 0xca, 0xd2, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0x4e, 0x62, 0x03, 0xdb, 0x60, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0xe5, 0xa8, 0xad, 0x52, 0x78, 0x00, 0x00, 0x00,
}

func (m *SectionId) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SectionId) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SectionId) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SectionId != 0 {
		i = encodeVarintSectionId(dAtA, i, uint64(m.SectionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSectionId(dAtA []byte, offset int, v uint64) int {
	offset -= sovSectionId(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SectionId) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SectionId != 0 {
		n += 1 + sovSectionId(uint64(m.SectionId))
	}
	return n
}

func sovSectionId(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSectionId(x uint64) (n int) {
	return sovSectionId(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SectionId) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSectionId
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SectionId: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SectionId: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SectionId", wireType)
			}
			m.SectionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSectionId
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SectionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSectionId(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSectionId
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSectionId(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSectionId
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSectionId
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSectionId
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSectionId
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSectionId
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSectionId
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSectionId        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSectionId          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSectionId = fmt.Errorf("proto: unexpected end of group")
)
